# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in kitchen.gemspec
# gemspec

gem 'test-kitchen'
gem 'kitchen-salt'
gem 'kitchen-inspec'
gem 'kitchen-docker'